# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-30 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedInAPIClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_app', models.CharField(max_length=64, verbose_name='LinkedIn App')),
                ('api_call_url', models.URLField(null=True, verbose_name='LinkedIn API Auth URL')),
                ('client_id', models.CharField(max_length=64, unique=True, verbose_name='Client ID')),
                ('client_secret', models.CharField(max_length=64, unique=True, verbose_name='Client Secret')),
                ('redirect_uri', models.URLField(null=True, verbose_name='Redirect URI')),
                ('state', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('access_token', models.CharField(editable=False, max_length=1024, null=True)),
                ('expires_in', models.PositiveIntegerField(editable=False, null=True)),
            ],
            options={
                'verbose_name': 'LinkedIn API Client',
            },
        ),
        migrations.CreateModel(
            name='MarkdownText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_section', models.CharField(max_length=20)),
                ('content', markdownx.models.MarkdownxField()),
            ],
            options={
                'verbose_name': 'Markdown Text',
            },
        ),
        migrations.CreateModel(
            name='NavigablePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Navigable Page',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='TextPage',
            fields=[
                ('navigablepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homepage.NavigablePage')),
                ('content', markdownx.models.MarkdownxField()),
            ],
            options={
                'verbose_name': 'Text Page',
            },
            bases=('homepage.navigablepage',),
        ),
        migrations.CreateModel(
            name='LinkedInAPITextPage',
            fields=[
                ('textpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homepage.TextPage')),
                ('profile_id', models.CharField(max_length=80, null=True, unique=True)),
                ('headline', models.CharField(max_length=256, null=True)),
                ('industry', models.CharField(max_length=256, null=True)),
                ('summary', models.CharField(max_length=2048, null=True)),
                ('current_job_description', models.CharField(max_length=1024, null=True)),
                ('profile_url', models.URLField(null=True)),
            ],
            options={
                'verbose_name': 'LinkedIn API Text Page',
            },
            bases=('homepage.textpage',),
        ),
    ]
