# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-23 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarkdownText',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('target_section', models.CharField(max_length=20)),
                ('content', markdownx.models.MarkdownxField()),
            ],
        ),
        migrations.CreateModel(
            name='NavigablePage',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='TextPage',
            fields=[
                ('navigablepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                           parent_link=True, primary_key=True, serialize=False, to='homepage.NavigablePage')),
                ('content', markdownx.models.MarkdownxField()),
            ],
            bases=('homepage.navigablepage',),
        ),
    ]
