# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-23 11:48
from __future__ import unicode_literals
import os

from django.db import migrations


def migrate(apps, schema_editor):
    """
    Create webpages automatically with migrations.
    """
    db_alias = schema_editor.connection.alias

    TextPage = apps.get_model("homepage", "TextPage")
    MarkdownText = apps.get_model("homepage", "MarkdownText")

    md_folder = os.path.join(
        os.getcwd(), 'homepage', 'markdown')

    TextPage.objects.using(db_alias).create(
        title='Main Page',
        content="".join(open(os.path.join(
            md_folder, 'main-page.md')).readlines()),
        order=1,
        slug='main-page')
    TextPage.objects.using(db_alias).create(
        title='About Me',
        content="".join(open(os.path.join(
            md_folder, 'about-me.md')).readlines()),
        order=2,
        slug='about-me')
    TextPage.objects.using(db_alias).create(
        title='Career Bio',
        content="".join(open(os.path.join(
            md_folder, 'career-bio.md')).readlines()),
        order=3,
        slug='career-bio')

    MarkdownText.objects.using(db_alias).create(
        target_section='header',
        content="".join(open(os.path.join(md_folder, 'header.md')).readlines()))


def reverse_migration(apps, schema_editor):
    """
    Delete all created objects during roll-back.
    """
    db_alias = schema_editor.connection.alias

    TextPage = apps.get_model("homepage", "TextPage")
    MarkdownText = apps.get_model("homepage", "MarkdownText")

    TextPage.objects.using(db_alias).filter(title='Main Page').delete()
    TextPage.objects.using(db_alias).filter(title='About Me').delete()
    TextPage.objects.using(db_alias).filter(title='Career Bio').delete()
    MarkdownText.objects.using(db_alias).filter(
        target_section='header').delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            migrate,
            reverse_migration
        ),

    ]
