# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-19 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InheritedPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homepage.Page')),
                ('test', models.CharField(max_length=10)),
            ],
            bases=('homepage.page',),
        ),
    ]
