# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-14 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_markdowntext'),
    ]

    operations = [
        migrations.AddField(
            model_name='markdowntext',
            name='target_section',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
