# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-24 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_db_initialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedInAPIClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_app', models.CharField(max_length=64)),
                ('client_id', models.CharField(max_length=64, unique=True)),
                ('client_secret', models.CharField(max_length=64, unique=True)),
                ('redirect_uri', models.URLField()),
                ('state', models.CharField(max_length=64)),
                ('authorization_code', models.CharField(max_length=1024)),
                ('access_token', models.CharField(max_length=1024)),
                ('expires_in', models.PositiveIntegerField()),
            ],
        ),
    ]
