# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-24 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_linkedinapiclient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkedinapiclient',
            options={'verbose_name': 'LinkedIn API Client'},
        ),
        migrations.AlterModelOptions(
            name='markdowntext',
            options={'verbose_name': 'Markdown Text'},
        ),
        migrations.AlterModelOptions(
            name='navigablepage',
            options={'ordering': ('order',), 'verbose_name': 'Navigable Page'},
        ),
        migrations.AlterModelOptions(
            name='textpage',
            options={'verbose_name': 'Text Page'},
        ),
        migrations.AlterField(
            model_name='linkedinapiclient',
            name='access_token',
            field=models.CharField(max_length=1024, verbose_name='Access Token'),
        ),
        migrations.AlterField(
            model_name='linkedinapiclient',
            name='authorization_code',
            field=models.CharField(max_length=1024, verbose_name='Authorization Code'),
        ),
        migrations.AlterField(
            model_name='linkedinapiclient',
            name='client_id',
            field=models.CharField(max_length=64, unique=True, verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='linkedinapiclient',
            name='client_secret',
            field=models.CharField(max_length=64, unique=True, verbose_name='Client Secret'),
        ),
        migrations.AlterField(
            model_name='linkedinapiclient',
            name='expires_in',
            field=models.PositiveIntegerField(verbose_name='Expires In'),
        ),
        migrations.AlterField(
            model_name='linkedinapiclient',
            name='linkedin_app',
            field=models.CharField(max_length=64, verbose_name='LinkedIn App'),
        ),
        migrations.AlterField(
            model_name='linkedinapiclient',
            name='redirect_uri',
            field=models.URLField(verbose_name='Redirect URI'),
        ),
        migrations.AlterField(
            model_name='linkedinapiclient',
            name='state',
            field=models.UUIDField(),
        ),
    ]
