# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-24 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20171224_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedinapiclient',
            name='state',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
