# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-24 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20171224_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedinapiclient',
            name='access_token',
            field=models.CharField(editable=False, max_length=1024, null=True, verbose_name='Access Token'),
        ),
        migrations.AlterField(
            model_name='linkedinapiclient',
            name='authorization_code',
            field=models.CharField(editable=False, max_length=1024, null=True, verbose_name='Authorization Code'),
        ),
        migrations.AlterField(
            model_name='linkedinapiclient',
            name='expires_in',
            field=models.PositiveIntegerField(editable=False, null=True, verbose_name='Expires In'),
        ),
    ]
